### ISSUE TITLE
faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server.userException

### ISSUE THREAD

**Issue by keanuyaoo** [rombert/mantis-axis-soap-client#2]
I have troubles when call MantisConnect with this lib,

The Exception Message is:

```
AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server.userException
 faultSubcode: 
 faultString: org.xml.sax.SAXException: Processing instructions are not allowed within SOAP messages
 faultActor: 
 faultNode: 
 faultDetail: 
	{http://xml.apache.org/axis/}stackTrace:org.xml.sax.SAXException: Processing instructions are not allowed within SOAP messages
	at org.apache.axis.encoding.DeserializationContext.processingInstruction(DeserializationContext.java:982)
```

It seems that some not supported instructions in SOAP messages;

My env is:
      MantisBT Version:1.3.0
      JDK Version:1.7

My Sample Code:
```
new MantisConnectLocator().getMantisConnectPort(uri).mc_enum_priorities(username,password);
```

I change the src/wsdl file to V1.3.0 , and build a new jar ,It not work too;
I also try it with JDK 1.6, It also not work;

I need your help!  Thanks!

**Comment by keanuyaoo** [comment]
I have solve it; I make a mistake;
Sorry for interrup

**Comment by rombert** [comment]
Good to hear you solved it! Out of curiousity, what was the issue? It might help others hitting the same problem.
